-- ===============================================================================
-- ArogyaStock Sentinel - Oracle Database Schema (Master/Operational Split)
-- ===============================================================================

-- 1. CENTERS Table
-- Master data for Health Centers
CREATE TABLE centers (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(30) NOT NULL,
    location VARCHAR2(30),
    is_active NUMBER(1) DEFAULT 1 CHECK (is_active IN (0, 1))
);

-- 2. USERS Table
-- Stores all users with role-based access
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(30) NOT NULL,
    email VARCHAR2(40) UNIQUE NOT NULL,
    mobile VARCHAR2(15),
    username VARCHAR2(20) UNIQUE NOT NULL,
    password_hash VARCHAR2(60) NOT NULL,
    role VARCHAR2(10) CHECK (role IN ('ADMIN', 'STAFF', 'VIEWER')) NOT NULL,
    center_id NUMBER,
    designation VARCHAR2(20),
    employee_id VARCHAR2(20),
    organization_name VARCHAR2(30),
    is_active NUMBER(1) DEFAULT 1 CHECK (is_active IN (0, 1)),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_users_center FOREIGN KEY (center_id) REFERENCES centers(id) ON DELETE SET NULL
);

-- 3. MEDICINES Table (Master Data - ADMIN Only)
-- Definition of medicines available in the system
CREATE TABLE medicines (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(40) UNIQUE NOT NULL,
    category VARCHAR2(20),
    threshold_quantity NUMBER DEFAULT 0 NOT NULL,
    is_active NUMBER(1) DEFAULT 1 CHECK (is_active IN (0, 1)),
    created_by NUMBER, -- FK to users.id (Admin who added it)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_med_creator FOREIGN KEY (created_by) REFERENCES users(id)
);

-- 4. BATCHES Table (Operational Data - STAFF Controlled)
-- Tracking specific batches of medicines at each center
CREATE TABLE batches (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicine_id NUMBER NOT NULL,
    center_id NUMBER NOT NULL,
    batch_number VARCHAR2(20) NOT NULL,
    expiry_date DATE NOT NULL,
    quantity_remaining NUMBER DEFAULT 0 NOT NULL CHECK (quantity_remaining >= 0),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_center_med_batch UNIQUE (center_id, medicine_id, batch_number),
    CONSTRAINT fk_batch_med FOREIGN KEY (medicine_id) REFERENCES medicines(id),
    CONSTRAINT fk_batch_center FOREIGN KEY (center_id) REFERENCES centers(id)
);

-- 5. STOCK_TRANSACTIONS Table (Operational History)
-- Log of every IN (receipt) and OUT (dispatch/consumption) action
CREATE TABLE stock_transactions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicine_id NUMBER NOT NULL,
    batch_id NUMBER NOT NULL,
    center_id NUMBER NOT NULL,
    transaction_type VARCHAR2(10) CHECK (transaction_type IN ('IN', 'OUT')) NOT NULL,
    quantity NUMBER NOT NULL CHECK (quantity > 0),
    transaction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by NUMBER NOT NULL, -- References users.id (Staff who performed it)
    remarks VARCHAR2(50),
    CONSTRAINT fk_trans_med FOREIGN KEY (medicine_id) REFERENCES medicines(id),
    CONSTRAINT fk_trans_batch FOREIGN KEY (batch_id) REFERENCES batches(id),
    CONSTRAINT fk_trans_center FOREIGN KEY (center_id) REFERENCES centers(id),
    CONSTRAINT fk_trans_user FOREIGN KEY (created_by) REFERENCES users(id)
);

-- 6. ALERTS Table
-- Automatically generated alerts
CREATE TABLE alerts (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    center_id NUMBER NOT NULL,
    medicine_id NUMBER NOT NULL,
    alert_type VARCHAR2(20) NOT NULL,
    alert_message VARCHAR2(60) NOT NULL,
    severity VARCHAR2(15) NOT NULL,
    status VARCHAR2(15) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP,
    resolved_by NUMBER,
    CONSTRAINT fk_alert_center FOREIGN KEY (center_id) REFERENCES centers(id),
    CONSTRAINT fk_alert_med FOREIGN KEY (medicine_id) REFERENCES medicines(id),
    CONSTRAINT fk_alert_resolver FOREIGN KEY (resolved_by) REFERENCES users(id)
);

-- ===============================================================================
-- Initial Seeding
-- ===============================================================================
-- 1. Centers
INSERT INTO centers (id, name, location) VALUES (1, 'PHC_Dist_A', 'District');
INSERT INTO centers (id, name, location) VALUES (2, 'PHC_Rural_B', 'Rural');

-- 2. Medicines (Master List)
INSERT INTO medicines (name, category, threshold_quantity, is_active) VALUES ('Paracetamol 500mg', 'Analgesic', 500, 1);
INSERT INTO medicines (name, category, threshold_quantity, is_active) VALUES ('Amoxicillin 250mg', 'Antibiotic', 200, 1);
INSERT INTO medicines (name, category, threshold_quantity, is_active) VALUES ('Cetirizine 10mg', 'Antihistamine', 300, 1);
INSERT INTO medicines (name, category, threshold_quantity, is_active) VALUES ('Ibuprofen 400mg', 'NSAID', 400, 1);
INSERT INTO medicines (name, category, threshold_quantity, is_active) VALUES ('Metformin 500mg', 'Antidiabetic', 1000, 1);
INSERT INTO medicines (name, category, threshold_quantity, is_active) VALUES ('Amlodipine 5mg', 'Antihypert', 600, 1);

COMMIT;
